kumuluzee:
  name: track-player
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  grpc:
    server:
      url: localhost
      http:
        port: 8443

  health:
    checks:
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: track-player-endpoint
      url-pattern: /v1/track-player/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="track player">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="356eb699-3e3f-41de-8320-cc629213e328-ls.logit.io"
                            port="20166" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'
app-properties:
  external-services:
    enabled: true
  healthy: true
