kumuluzee:
  name: track-player
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: track-player-endpoint
      url-pattern: /v1/track-player/*

app-properties:
  external-services:
    enabled: true
  healthy: true
