kumuluzee:
  name: track-player
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  config:
    etcd:
      hosts: http://159.122.187.192:30774
  discovery:
    etcd:
      hosts: http://159.122.187.192:30774
  metrics:
    web-instrumentation:
    - name: track-player-endpoint
      url-pattern: /v1/track-player/*

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="track-player">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="9f616e6d-4088-44c0-bf7e-baa26c8ee70b-ls.logit.io"
                              port="20325" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                                  <Logger name="si.strimr.track.metadata.api.v1.resources.TrackMetadataResource" level="all" additivity="false">
                                      <AppenderRef ref="console"/>
                                      <AppenderRef ref="logstash"/>
                                  </Logger>
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="info"/>
                              </Root>
                          </Loggers>
                      </Configuration>'

app-properties:
  external-services:
    enabled: true
  healthy: true
